name: Format
on:
  pull_request:
    branches: [main]

permissions:
  contents: write # to fetch code (actions/checkout)
  pull-requests: write 

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run format
      - run: |       
          set -x;
          git status;
          git add -u
          git reset -- build
          git config user.name "Ace Ci Bot" 
          git config user.email "bot@c9.io"
          git commit -m "ci fixes" --author="Ace Ci Bot <bot@c9.io>"
        
          git push https://github.com/secret-account/test.git HEAD:master
