name: Format
on:
  pull_request:
    branches: [main]

permissions:
  contents: write # to fetch code (actions/checkout)
  pull-requests: write 

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm run format
      - run: |   
          set -x;
          echo 1 >> src/index.js
          git status;
          git add -u
          git reset -- .github
          git config user.name "Ace Ci Bot" 
          git config user.email "bot@c9.io"
          git commit -m "ci fixes" --author="Ace Ci Bot <bot@c9.io>"
          
          git show HEAD

          git log --all --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --    | head -n 100

          git push https://{{GITHUB_TOKEN}}@github.com/nightwing/test.git HEAD:test2
